"""Central French copy for the first interactive Gravity shell."""

APP_NAME = "GRAVITY"
SCENE_NAME = "Nuage galactique"
VISUAL_MILESTONE = "Jalon 3 · animation visuelle"
PAUSE = "Pause"
RESUME = "Reprendre"
RESTART = "Recommencer"
RESET_CAMERA = "Recentrer la vue"
POINT_SIZE = "Taille des étoiles"
ANIMATION_SPEED = "Vitesse visuelle"
CONTROLS = "Contrôles"
PERFORMANCE = "Performances"
GRAPHICS = "Carte graphique"
HELP = "Aide et commandes"
HIDE_SETTINGS = "Masquer les réglages"
SHOW_SETTINGS = "Réglages"
SYNTHETIC_NOTICE = "Ce nuage sert à valider le rendu. La gravitation réelle arrivera au jalon 4."
MOUSE_HELP = "Clic gauche : tourner · clic droit ou molette : déplacer · roue : zoomer"
