"""Central French copy for Gravity's interactive shell."""

APP_NAME = "GRAVITY"
SCENE_NAME = "Galaxie spirale"
VISUAL_MILESTONE = "Jalon 7 · gravitation réelle"
PAUSE = "Pause"
RESUME = "Reprendre"
RESTART = "Recommencer"
SINGLE_STEP = "Avancer d’un pas"
RESET_CAMERA = "Recentrer la vue"
POINT_SIZE = "Taille des étoiles"
ANIMATION_SPEED = "Vitesse de simulation"
CONTROLS = "Contrôles"
PERFORMANCE = "Performances"
GRAPHICS = "Carte graphique"
ADVANCED_PHYSICS = "Physique avancée"
HELP = "Aide et commandes"
HIDE_SETTINGS = "Masquer les réglages"
SHOW_SETTINGS = "Réglages"
PHYSICAL_NOTICE = "Les mouvements visibles proviennent maintenant du moteur gravitationnel."
BARNES_HUT_DEFAULT = "Mode normal · Barnes–Hut · 10’000 particules"
EXACT_TEST = "Tester le moteur exact · 1’000 particules"
EXACT_WARNING = (
    "Mode de comparaison volontairement limité à 1’000 particules. "
    "Il sert à confronter Barnes–Hut au calcul de référence."
)
BACK_TO_BARNES_HUT = "Revenir à Barnes–Hut · 10’000 particules"
MOUSE_HELP = "Clic gauche : tourner · clic droit ou molette : déplacer · roue : zoomer"
