"""Central French copy for Gravity's interactive shell."""

APP_NAME = "GRAVITY"
VISUAL_MILESTONE = "Jalon 9 · observer la physique"
PAUSE = "Pause"
RESUME = "Reprendre"
SINGLE_STEP = "Avancer d'un pas"
RESET_CAMERA = "Recentrer la vue"
POINT_SIZE = "Taille des étoiles"
ANIMATION_SPEED = "Vitesse de simulation"
CONTROLS = "Contrôles"
EXPERIMENT = "Expérience initiale"
INITIAL_SCENARIO = "Configuration de départ"
PARTICLE_COUNT = "Particules Barnes–Hut"
RANDOM_SEED = "Graine aléatoire"
APPLY_EXPERIMENT = "Appliquer et recommencer"
CHANGE_SEED = "Changer la graine"
PERFORMANCE = "Performances"
OBSERVATION = "Observation"
COLOR_MODE = "Couleurs"
CAMERA_VIEW = "Vue"
SHOW_CENTER = "Afficher le centre de masse"
PHYSICAL_STATS = "Statistiques physiques"
GRAPHICS = "Carte graphique"
ADVANCED_PHYSICS = "Physique avancée"
HELP = "Aide et commandes"
HIDE_SETTINGS = "Masquer les réglages"
SHOW_SETTINGS = "Réglages"
PHYSICAL_NOTICE = "Les mouvements visibles proviennent maintenant du moteur gravitationnel."
EXACT_TEST = "Tester le moteur exact · max. 1'000 particules"
EXACT_WARNING = (
    "Mode de comparaison volontairement limité à 1'000 particules, "
    "même si l'expérience Barnes–Hut en contient davantage. "
    "Il sert à confronter Barnes–Hut au calcul de référence."
)
BACK_TO_BARNES_HUT = "Revenir à Barnes–Hut"
KEYBOARD_HELP = "Espace : pause · R : recentrer · F : plein écran · Tab : réglages"
MOUSE_HELP = "Clic gauche : tourner · clic droit ou molette : déplacer · roue : zoomer"
