"""Analytic acceleration fields kept separate from particle self-gravity."""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np
import numpy.typing as npt
from numba import njit

from gravity.core.state import FloatArray


def _positive_finite(value: float, name: str, *, allow_zero: bool = False) -> float:
    try:
        converted = float(value)
    except (TypeError, ValueError) as error:
        raise TypeError(f"{name} must be a real number") from error
    valid = converted >= 0.0 if allow_zero else converted > 0.0
    if not math.isfinite(converted) or not valid:
        qualifier = "non-negative" if allow_zero else "strictly positive"
        raise ValueError(f"{name} must be finite and {qualifier}")
    return converted


def _validate_positions(positions: FloatArray) -> int:
    if not isinstance(positions, np.ndarray) or positions.dtype != np.float64:
        raise TypeError("positions must be a float64 NumPy array")
    if positions.ndim != 2 or positions.shape[1:] != (3,):
        raise ValueError("positions must have shape (N, 3)")
    if not positions.flags.c_contiguous:
        raise ValueError("positions must be C-contiguous")
    if not np.all(np.isfinite(positions)):
        raise ValueError("positions must contain only finite values")
    return int(positions.shape[0])


def _prepare_output(
    positions: FloatArray,
    particle_count: int,
    output_buffer: FloatArray | None,
) -> FloatArray:
    if output_buffer is None:
        return np.empty((particle_count, 3), dtype=np.float64)
    if not isinstance(output_buffer, np.ndarray) or output_buffer.dtype != np.float64:
        raise TypeError("output_buffer must be a float64 NumPy array")
    if output_buffer.shape != (particle_count, 3):
        raise ValueError(f"output_buffer must have shape ({particle_count}, 3)")
    if not output_buffer.flags.c_contiguous or not output_buffer.flags.writeable:
        raise ValueError("output_buffer must be C-contiguous and writeable")
    if np.shares_memory(output_buffer, positions):
        raise ValueError("output_buffer cannot overlap positions")
    return output_buffer


@njit(cache=True, nogil=True)
def _plummer_acceleration_kernel(
    positions: FloatArray,
    mass: float,
    scale_radius_squared: float,
    output: FloatArray,
) -> None:
    for index in range(positions.shape[0]):
        x = positions[index, 0]
        y = positions[index, 1]
        z = positions[index, 2]
        softened_squared_radius = x * x + y * y + z * z + scale_radius_squared
        scale = -mass / (softened_squared_radius * math.sqrt(softened_squared_radius))
        output[index, 0] = x * scale
        output[index, 1] = y * scale
        output[index, 2] = z * scale


@njit(cache=True, nogil=True)
def _add_plummer_acceleration_kernel(
    positions: FloatArray,
    mass: float,
    scale_radius_squared: float,
    output: FloatArray,
) -> None:
    for index in range(positions.shape[0]):
        x = positions[index, 0]
        y = positions[index, 1]
        z = positions[index, 2]
        softened_squared_radius = x * x + y * y + z * z + scale_radius_squared
        scale = -mass / (softened_squared_radius * math.sqrt(softened_squared_radius))
        output[index, 0] += x * scale
        output[index, 1] += y * scale
        output[index, 2] += z * scale


@dataclass(frozen=True, slots=True)
class PlummerPotential:
    """Finite spherical background potential with total asymptotic mass."""

    mass: float
    scale_radius: float
    name: str = "plummer"

    def __post_init__(self) -> None:
        object.__setattr__(self, "mass", _positive_finite(self.mass, "mass", allow_zero=True))
        object.__setattr__(
            self,
            "scale_radius",
            _positive_finite(self.scale_radius, "scale_radius"),
        )

    def enclosed_mass(self, radius: npt.ArrayLike) -> FloatArray:
        """Return the equivalent mass enclosed by each non-negative radius."""

        radii = np.asarray(radius, dtype=np.float64)
        if not np.all(np.isfinite(radii)) or np.any(radii < 0.0):
            raise ValueError("radius must contain only finite non-negative values")
        squared_radius = radii * radii
        denominator = (squared_radius + self.scale_radius**2) ** 1.5
        result = self.mass * radii * squared_radius / denominator
        return np.ascontiguousarray(result, dtype=np.float64)

    def acceleration(
        self,
        positions: FloatArray,
        output_buffer: FloatArray | None = None,
    ) -> FloatArray:
        """Fill and return the acceleration generated by this potential."""

        particle_count = _validate_positions(positions)
        output = _prepare_output(positions, particle_count, output_buffer)
        _plummer_acceleration_kernel(
            positions,
            self.mass,
            self.scale_radius * self.scale_radius,
            output,
        )
        if not np.all(np.isfinite(output)):
            raise FloatingPointError("Plummer potential produced a non-finite acceleration")
        return output

    def add_acceleration(self, positions: FloatArray, output_buffer: FloatArray) -> None:
        """Add this field to an existing solver output in place."""

        particle_count = _validate_positions(positions)
        output = _prepare_output(positions, particle_count, output_buffer)
        if not np.all(np.isfinite(output)):
            raise ValueError("output_buffer must contain only finite values before addition")
        _add_plummer_acceleration_kernel(
            positions,
            self.mass,
            self.scale_radius * self.scale_radius,
            output,
        )
        if not np.all(np.isfinite(output)):
            raise FloatingPointError("Plummer potential produced a non-finite acceleration")
